name: import_supabase
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=2.12.0 <3.0.0"

# dependencies:
#   path: ^1.8.0
dev_dependencies:
  build_runner: ^2.1.1
  json_serializable: ^5.0.0
  pedantic: ^1.10.0
  smartstruct_generator: ^1.2.3+1
dependencies:
  args: ^2.2.0
  dotenv: ^3.0.0
  json_annotation: ^4.1.0
  smartstruct: ^1.2.3+1
  supabase: ^0.2.4
